[package]
name = "peer_allocation"
type = "contract"
authors = ["AztecForge"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v4.2.0", directory = "aztec" }
token = { path = "../token" }
