
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BountyBoardContractArtifactJson from '../../../contracts/target/bounty-BountyBoard.json' with { type: 'json' };
export const BountyBoardContractArtifact = loadContractArtifact(BountyBoardContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract BountyBoard;
 */
export class BountyBoardContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BountyBoardContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BountyBoardContract {
    return Contract.at(address, BountyBoardContract.artifact, wallet) as BountyBoardContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<BountyBoardContract>(PublicKeys.default(), wallet, BountyBoardContractArtifact, (instance, wallet) => BountyBoardContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<BountyBoardContract>(publicKeys, wallet, BountyBoardContractArtifact, (instance, wallet) => BountyBoardContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BountyBoardContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BountyBoardContract['methods'][M]>
  ) {
    return new DeployMethod<BountyBoardContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BountyBoardContractArtifact,
      (instance, wallet) => BountyBoardContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BountyBoardContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BountyBoardContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'bounty_count' | 'bounty_creators' | 'bounty_tokens' | 'bounty_amounts' | 'bounty_deadlines' | 'bounty_descriptions' | 'bounty_statuses' | 'bounty_is_amount_public' | 'bounty_claimers' | 'bounty_submissions' | 'bounty_escrows' | 'total_bounties_posted' | 'total_bounties_completed' | 'total_value_escrowed' | 'total_value_paid'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
bounty_count: {
      slot: new Fr(3n),
    },
bounty_creators: {
      slot: new Fr(4n),
    },
bounty_tokens: {
      slot: new Fr(5n),
    },
bounty_amounts: {
      slot: new Fr(6n),
    },
bounty_deadlines: {
      slot: new Fr(7n),
    },
bounty_descriptions: {
      slot: new Fr(8n),
    },
bounty_statuses: {
      slot: new Fr(9n),
    },
bounty_is_amount_public: {
      slot: new Fr(10n),
    },
bounty_claimers: {
      slot: new Fr(11n),
    },
bounty_submissions: {
      slot: new Fr(12n),
    },
bounty_escrows: {
      slot: new Fr(13n),
    },
total_bounties_posted: {
      slot: new Fr(14n),
    },
total_bounties_completed: {
      slot: new Fr(15n),
    },
total_value_escrowed: {
      slot: new Fr(16n),
    },
total_value_paid: {
      slot: new Fr(17n),
    }
      } as ContractStorageLayout<'admin' | 'bounty_count' | 'bounty_creators' | 'bounty_tokens' | 'bounty_amounts' | 'bounty_deadlines' | 'bounty_descriptions' | 'bounty_statuses' | 'bounty_is_amount_public' | 'bounty_claimers' | 'bounty_submissions' | 'bounty_escrows' | 'total_bounties_posted' | 'total_bounties_completed' | 'total_value_escrowed' | 'total_value_paid'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** approve_submission(bounty_id: integer) */
    approve_submission: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_bounty(bounty_id: integer) */
    cancel_bounty: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_bounty(bounty_id: integer) */
    claim_bounty: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_bounty(payment_token: struct, reward_amount: integer, description_hash: field, deadline_block: integer, is_amount_public: boolean, authwit_nonce: field) */
    create_bounty: ((payment_token: AztecAddressLike, reward_amount: (bigint | number), description_hash: FieldLike, deadline_block: (bigint | number), is_amount_public: boolean, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** dispute_bounty(bounty_id: integer) */
    dispute_bounty: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_amount(bounty_id: integer) */
    get_bounty_amount: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_claimer(bounty_id: integer) */
    get_bounty_claimer: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_count() */
    get_bounty_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_creator(bounty_id: integer) */
    get_bounty_creator: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_deadline(bounty_id: integer) */
    get_bounty_deadline: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_description(bounty_id: integer) */
    get_bounty_description: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_status(bounty_id: integer) */
    get_bounty_status: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_submission(bounty_id: integer) */
    get_bounty_submission: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounty_token(bounty_id: integer) */
    get_bounty_token: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_escrow_balance(bounty_id: integer) */
    get_escrow_balance: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_bounties_completed() */
    get_total_bounties_completed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_bounties_posted() */
    get_total_bounties_posted: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_value_escrowed() */
    get_total_value_escrowed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_value_paid() */
    get_total_value_paid: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_amount_public(bounty_id: integer) */
    is_amount_public: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** reject_submission(bounty_id: integer) */
    reject_submission: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** resolve_dispute(bounty_id: integer, approve: boolean) */
    resolve_dispute: ((bounty_id: (bigint | number), approve: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** submit_work(bounty_id: integer, submission_hash: field) */
    submit_work: ((bounty_id: (bigint | number), submission_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unclaim_bounty(bounty_id: integer) */
    unclaim_bounty: ((bounty_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
