
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import FundingPoolContractArtifactJson from '../../../contracts/target/funding_pool-FundingPool.json' with { type: 'json' };
export const FundingPoolContractArtifact = loadContractArtifact(FundingPoolContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract FundingPool;
 */
export class FundingPoolContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, FundingPoolContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): FundingPoolContract {
    return Contract.at(address, FundingPoolContract.artifact, wallet) as FundingPoolContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<FundingPoolContract>(PublicKeys.default(), wallet, FundingPoolContractArtifact, (instance, wallet) => FundingPoolContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<FundingPoolContract>(publicKeys, wallet, FundingPoolContractArtifact, (instance, wallet) => FundingPoolContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof FundingPoolContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<FundingPoolContract['methods'][M]>
  ) {
    return new DeployMethod<FundingPoolContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      FundingPoolContractArtifact,
      (instance, wallet) => FundingPoolContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return FundingPoolContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(FundingPoolContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'pool_count' | 'pool_curators' | 'pool_tokens' | 'pool_purpose_hashes' | 'pool_types' | 'pool_statuses' | 'pool_total_deposited' | 'pool_total_disbursed' | 'pool_contributor_count' | 'pool_recipient_count' | 'deposit_amounts' | 'allocation_amounts' | 'total_pools_created' | 'total_value_deposited' | 'total_value_disbursed'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
pool_count: {
      slot: new Fr(3n),
    },
pool_curators: {
      slot: new Fr(4n),
    },
pool_tokens: {
      slot: new Fr(5n),
    },
pool_purpose_hashes: {
      slot: new Fr(6n),
    },
pool_types: {
      slot: new Fr(7n),
    },
pool_statuses: {
      slot: new Fr(8n),
    },
pool_total_deposited: {
      slot: new Fr(9n),
    },
pool_total_disbursed: {
      slot: new Fr(10n),
    },
pool_contributor_count: {
      slot: new Fr(11n),
    },
pool_recipient_count: {
      slot: new Fr(12n),
    },
deposit_amounts: {
      slot: new Fr(13n),
    },
allocation_amounts: {
      slot: new Fr(14n),
    },
total_pools_created: {
      slot: new Fr(15n),
    },
total_value_deposited: {
      slot: new Fr(16n),
    },
total_value_disbursed: {
      slot: new Fr(17n),
    }
      } as ContractStorageLayout<'admin' | 'pool_count' | 'pool_curators' | 'pool_tokens' | 'pool_purpose_hashes' | 'pool_types' | 'pool_statuses' | 'pool_total_deposited' | 'pool_total_disbursed' | 'pool_contributor_count' | 'pool_recipient_count' | 'deposit_amounts' | 'allocation_amounts' | 'total_pools_created' | 'total_value_deposited' | 'total_value_disbursed'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** allocate(pool_id: integer, recipient: struct, amount: integer, reason_hash: field) */
    allocate: ((pool_id: (bigint | number), recipient: AztecAddressLike, amount: (bigint | number), reason_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** close_pool(pool_id: integer) */
    close_pool: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_pool(payment_token: struct, purpose_hash: field, pool_type: integer) */
    create_pool: ((payment_token: AztecAddressLike, purpose_hash: FieldLike, pool_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit(pool_id: integer, amount: integer, authwit_nonce: field) */
    deposit: ((pool_id: (bigint | number), amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_allocation(pool_id: integer, recipient: struct) */
    get_allocation: ((pool_id: (bigint | number), recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_deposit(pool_id: integer, depositor: struct) */
    get_deposit: ((pool_id: (bigint | number), depositor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_available_balance(pool_id: integer) */
    get_pool_available_balance: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_contributor_count(pool_id: integer) */
    get_pool_contributor_count: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_count() */
    get_pool_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_curator(pool_id: integer) */
    get_pool_curator: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_recipient_count(pool_id: integer) */
    get_pool_recipient_count: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_status(pool_id: integer) */
    get_pool_status: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_total_deposited(pool_id: integer) */
    get_pool_total_deposited: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_total_disbursed(pool_id: integer) */
    get_pool_total_disbursed: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pool_type(pool_id: integer) */
    get_pool_type: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_pools_created() */
    get_total_pools_created: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_value_deposited() */
    get_total_value_deposited: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_value_disbursed() */
    get_total_value_disbursed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pause_pool(pool_id: integer) */
    pause_pool: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** resume_pool(pool_id: integer) */
    resume_pool: ((pool_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw(pool_id: integer, amount: integer) */
    withdraw: ((pool_id: (bigint | number), amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
