
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import HackathonEngineContractArtifactJson from '../../../contracts/target/hackathon-HackathonEngine.json' with { type: 'json' };
export const HackathonEngineContractArtifact = loadContractArtifact(HackathonEngineContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract HackathonEngine;
 */
export class HackathonEngineContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, HackathonEngineContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): HackathonEngineContract {
    return Contract.at(address, HackathonEngineContract.artifact, wallet) as HackathonEngineContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<HackathonEngineContract>(PublicKeys.default(), wallet, HackathonEngineContractArtifact, (instance, wallet) => HackathonEngineContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<HackathonEngineContract>(publicKeys, wallet, HackathonEngineContractArtifact, (instance, wallet) => HackathonEngineContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof HackathonEngineContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<HackathonEngineContract['methods'][M]>
  ) {
    return new DeployMethod<HackathonEngineContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      HackathonEngineContractArtifact,
      (instance, wallet) => HackathonEngineContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return HackathonEngineContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(HackathonEngineContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'hackathon_count' | 'hackathon_organizers' | 'hackathon_name_hashes' | 'hackathon_description_hashes' | 'hackathon_tokens' | 'hackathon_prize_pools' | 'hackathon_statuses' | 'hackathon_submission_deadlines' | 'hackathon_judging_deadlines' | 'hackathon_team_counts' | 'hackathon_submission_counts' | 'hackathon_prize_paid' | 'hackathon_track_counts' | 'track_name_hashes' | 'track_description_hashes' | 'track_submission_counts' | 'team_count_per_hackathon' | 'team_leads' | 'team_name_hashes' | 'team_member_counts' | 'team_members' | 'submission_count_per_hackathon' | 'submission_team_ids' | 'submission_track_indices' | 'submission_project_hashes' | 'submission_repo_hashes' | 'submission_demo_hashes' | 'judge_registered' | 'hackathon_judge_counts' | 'judge_scores' | 'judge_scored' | 'submission_total_scores' | 'submission_score_counts' | 'prize_amounts' | 'prize_placements' | 'prize_claimed'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
hackathon_count: {
      slot: new Fr(3n),
    },
hackathon_organizers: {
      slot: new Fr(4n),
    },
hackathon_name_hashes: {
      slot: new Fr(5n),
    },
hackathon_description_hashes: {
      slot: new Fr(6n),
    },
hackathon_tokens: {
      slot: new Fr(7n),
    },
hackathon_prize_pools: {
      slot: new Fr(8n),
    },
hackathon_statuses: {
      slot: new Fr(9n),
    },
hackathon_submission_deadlines: {
      slot: new Fr(10n),
    },
hackathon_judging_deadlines: {
      slot: new Fr(11n),
    },
hackathon_team_counts: {
      slot: new Fr(12n),
    },
hackathon_submission_counts: {
      slot: new Fr(13n),
    },
hackathon_prize_paid: {
      slot: new Fr(14n),
    },
hackathon_track_counts: {
      slot: new Fr(15n),
    },
track_name_hashes: {
      slot: new Fr(16n),
    },
track_description_hashes: {
      slot: new Fr(17n),
    },
track_submission_counts: {
      slot: new Fr(18n),
    },
team_count_per_hackathon: {
      slot: new Fr(19n),
    },
team_leads: {
      slot: new Fr(20n),
    },
team_name_hashes: {
      slot: new Fr(21n),
    },
team_member_counts: {
      slot: new Fr(22n),
    },
team_members: {
      slot: new Fr(23n),
    },
submission_count_per_hackathon: {
      slot: new Fr(24n),
    },
submission_team_ids: {
      slot: new Fr(25n),
    },
submission_track_indices: {
      slot: new Fr(26n),
    },
submission_project_hashes: {
      slot: new Fr(27n),
    },
submission_repo_hashes: {
      slot: new Fr(28n),
    },
submission_demo_hashes: {
      slot: new Fr(29n),
    },
judge_registered: {
      slot: new Fr(30n),
    },
hackathon_judge_counts: {
      slot: new Fr(31n),
    },
judge_scores: {
      slot: new Fr(32n),
    },
judge_scored: {
      slot: new Fr(33n),
    },
submission_total_scores: {
      slot: new Fr(34n),
    },
submission_score_counts: {
      slot: new Fr(35n),
    },
prize_amounts: {
      slot: new Fr(36n),
    },
prize_placements: {
      slot: new Fr(37n),
    },
prize_claimed: {
      slot: new Fr(38n),
    }
      } as ContractStorageLayout<'admin' | 'hackathon_count' | 'hackathon_organizers' | 'hackathon_name_hashes' | 'hackathon_description_hashes' | 'hackathon_tokens' | 'hackathon_prize_pools' | 'hackathon_statuses' | 'hackathon_submission_deadlines' | 'hackathon_judging_deadlines' | 'hackathon_team_counts' | 'hackathon_submission_counts' | 'hackathon_prize_paid' | 'hackathon_track_counts' | 'track_name_hashes' | 'track_description_hashes' | 'track_submission_counts' | 'team_count_per_hackathon' | 'team_leads' | 'team_name_hashes' | 'team_member_counts' | 'team_members' | 'submission_count_per_hackathon' | 'submission_team_ids' | 'submission_track_indices' | 'submission_project_hashes' | 'submission_repo_hashes' | 'submission_demo_hashes' | 'judge_registered' | 'hackathon_judge_counts' | 'judge_scores' | 'judge_scored' | 'submission_total_scores' | 'submission_score_counts' | 'prize_amounts' | 'prize_placements' | 'prize_claimed'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_judge(hackathon_id: integer, judge: struct) */
    add_judge: ((hackathon_id: (bigint | number), judge: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** add_track(hackathon_id: integer, name_hash: field, description_hash: field) */
    add_track: ((hackathon_id: (bigint | number), name_hash: FieldLike, description_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** award_prize(hackathon_id: integer, team_id: integer, placement: integer, prize_amount: integer) */
    award_prize: ((hackathon_id: (bigint | number), team_id: (bigint | number), placement: (bigint | number), prize_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_prize(hackathon_id: integer, team_id: integer) */
    claim_prize: ((hackathon_id: (bigint | number), team_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_hackathon(name_hash: field, description_hash: field, payment_token: struct, total_prize_pool: integer, submission_deadline: integer, judging_deadline: integer, authwit_nonce: field) */
    create_hackathon: ((name_hash: FieldLike, description_hash: FieldLike, payment_token: AztecAddressLike, total_prize_pool: (bigint | number), submission_deadline: (bigint | number), judging_deadline: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_hackathon(hackathon_id: integer) */
    finalize_hackathon: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hackathon_count() */
    get_hackathon_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hackathon_organizer(hackathon_id: integer) */
    get_hackathon_organizer: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hackathon_prize_pool(hackathon_id: integer) */
    get_hackathon_prize_pool: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hackathon_status(hackathon_id: integer) */
    get_hackathon_status: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hackathon_submission_count(hackathon_id: integer) */
    get_hackathon_submission_count: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hackathon_team_count(hackathon_id: integer) */
    get_hackathon_team_count: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_prize_amount(hackathon_id: integer, team_id: integer) */
    get_prize_amount: ((hackathon_id: (bigint | number), team_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_prize_placement(hackathon_id: integer, team_id: integer) */
    get_prize_placement: ((hackathon_id: (bigint | number), team_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_submission_average_score(hackathon_id: integer, submission_id: integer) */
    get_submission_average_score: ((hackathon_id: (bigint | number), submission_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_judge(hackathon_id: integer, judge: struct) */
    is_judge: ((hackathon_id: (bigint | number), judge: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_team(hackathon_id: integer, team_name_hash: field) */
    register_team: ((hackathon_id: (bigint | number), team_name_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** score_submission(hackathon_id: integer, submission_id: integer, score: integer) */
    score_submission: ((hackathon_id: (bigint | number), submission_id: (bigint | number), score: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_building_phase(hackathon_id: integer) */
    start_building_phase: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_judging_phase(hackathon_id: integer) */
    start_judging_phase: ((hackathon_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** submit_project(hackathon_id: integer, team_id: integer, track_index: integer, project_hash: field, repo_hash: field, demo_hash: field) */
    submit_project: ((hackathon_id: (bigint | number), team_id: (bigint | number), track_index: (bigint | number), project_hash: FieldLike, repo_hash: FieldLike, demo_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
