
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PeerAllocationContractArtifactJson from '../../../contracts/target/peer_allocation-PeerAllocation.json' with { type: 'json' };
export const PeerAllocationContractArtifact = loadContractArtifact(PeerAllocationContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PeerAllocation;
 */
export class PeerAllocationContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PeerAllocationContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PeerAllocationContract {
    return Contract.at(address, PeerAllocationContract.artifact, wallet) as PeerAllocationContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PeerAllocationContract>(PublicKeys.default(), wallet, PeerAllocationContractArtifact, (instance, wallet) => PeerAllocationContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PeerAllocationContract>(publicKeys, wallet, PeerAllocationContractArtifact, (instance, wallet) => PeerAllocationContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PeerAllocationContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PeerAllocationContract['methods'][M]>
  ) {
    return new DeployMethod<PeerAllocationContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PeerAllocationContractArtifact,
      (instance, wallet) => PeerAllocationContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PeerAllocationContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PeerAllocationContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'circle_count' | 'circle_admins' | 'circle_tokens' | 'circle_epoch_durations' | 'circle_current_epochs' | 'circle_member_counts' | 'circle_give_per_member' | 'circle_reward_pools' | 'circle_total_distributed' | 'circle_statuses' | 'is_member' | 'give_amounts' | 'give_spent' | 'give_received' | 'epoch_total_give' | 'epoch_claimed' | 'epoch_reward_deposited'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
circle_count: {
      slot: new Fr(3n),
    },
circle_admins: {
      slot: new Fr(4n),
    },
circle_tokens: {
      slot: new Fr(5n),
    },
circle_epoch_durations: {
      slot: new Fr(6n),
    },
circle_current_epochs: {
      slot: new Fr(7n),
    },
circle_member_counts: {
      slot: new Fr(8n),
    },
circle_give_per_member: {
      slot: new Fr(9n),
    },
circle_reward_pools: {
      slot: new Fr(10n),
    },
circle_total_distributed: {
      slot: new Fr(11n),
    },
circle_statuses: {
      slot: new Fr(12n),
    },
is_member: {
      slot: new Fr(13n),
    },
give_amounts: {
      slot: new Fr(14n),
    },
give_spent: {
      slot: new Fr(15n),
    },
give_received: {
      slot: new Fr(16n),
    },
epoch_total_give: {
      slot: new Fr(17n),
    },
epoch_claimed: {
      slot: new Fr(18n),
    },
epoch_reward_deposited: {
      slot: new Fr(19n),
    }
      } as ContractStorageLayout<'admin' | 'circle_count' | 'circle_admins' | 'circle_tokens' | 'circle_epoch_durations' | 'circle_current_epochs' | 'circle_member_counts' | 'circle_give_per_member' | 'circle_reward_pools' | 'circle_total_distributed' | 'circle_statuses' | 'is_member' | 'give_amounts' | 'give_spent' | 'give_received' | 'epoch_total_give' | 'epoch_claimed' | 'epoch_reward_deposited'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_member(circle_id: integer, member: struct) */
    add_member: ((circle_id: (bigint | number), member: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** advance_epoch(circle_id: integer) */
    advance_epoch: ((circle_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** allocate_give(circle_id: integer, recipient: struct, amount: integer) */
    allocate_give: ((circle_id: (bigint | number), recipient: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_epoch_reward(circle_id: integer, epoch: integer) */
    claim_epoch_reward: ((circle_id: (bigint | number), epoch: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_circle(payment_token: struct, epoch_duration_blocks: integer, give_per_member: integer, reward_pool_per_epoch: integer) */
    create_circle: ((payment_token: AztecAddressLike, epoch_duration_blocks: (bigint | number), give_per_member: (bigint | number), reward_pool_per_epoch: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_circle_admin(circle_id: integer) */
    get_circle_admin: ((circle_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_circle_count() */
    get_circle_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_circle_current_epoch(circle_id: integer) */
    get_circle_current_epoch: ((circle_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_circle_member_count(circle_id: integer) */
    get_circle_member_count: ((circle_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_circle_reward_pool(circle_id: integer) */
    get_circle_reward_pool: ((circle_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_circle_total_distributed(circle_id: integer) */
    get_circle_total_distributed: ((circle_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_epoch_total_give(circle_id: integer, epoch: integer) */
    get_epoch_total_give: ((circle_id: (bigint | number), epoch: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_give_received(circle_id: integer, epoch: integer, member: struct) */
    get_give_received: ((circle_id: (bigint | number), epoch: (bigint | number), member: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_give_spent(circle_id: integer, epoch: integer, member: struct) */
    get_give_spent: ((circle_id: (bigint | number), epoch: (bigint | number), member: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** has_claimed(circle_id: integer, epoch: integer, member: struct) */
    has_claimed: ((circle_id: (bigint | number), epoch: (bigint | number), member: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_circle_member(circle_id: integer, member: struct) */
    is_circle_member: ((circle_id: (bigint | number), member: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_member(circle_id: integer, member: struct) */
    remove_member: ((circle_id: (bigint | number), member: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
