
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import QuestTrackerContractArtifactJson from '../../../contracts/target/quest-QuestTracker.json' with { type: 'json' };
export const QuestTrackerContractArtifact = loadContractArtifact(QuestTrackerContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract QuestTracker;
 */
export class QuestTrackerContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, QuestTrackerContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): QuestTrackerContract {
    return Contract.at(address, QuestTrackerContract.artifact, wallet) as QuestTrackerContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<QuestTrackerContract>(PublicKeys.default(), wallet, QuestTrackerContractArtifact, (instance, wallet) => QuestTrackerContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<QuestTrackerContract>(publicKeys, wallet, QuestTrackerContractArtifact, (instance, wallet) => QuestTrackerContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof QuestTrackerContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<QuestTrackerContract['methods'][M]>
  ) {
    return new DeployMethod<QuestTrackerContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      QuestTrackerContractArtifact,
      (instance, wallet) => QuestTrackerContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return QuestTrackerContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(QuestTrackerContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'quest_count' | 'quest_creators' | 'quest_name_hashes' | 'quest_description_hashes' | 'quest_types' | 'quest_tokens' | 'quest_rewards' | 'quest_max_completions' | 'quest_completion_counts' | 'quest_deadlines' | 'quest_statuses' | 'quest_reputation_gates' | 'quest_verifiers' | 'quest_completed_by' | 'quest_completion_proofs' | 'total_quests_created' | 'total_quests_completed' | 'total_rewards_paid'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
quest_count: {
      slot: new Fr(3n),
    },
quest_creators: {
      slot: new Fr(4n),
    },
quest_name_hashes: {
      slot: new Fr(5n),
    },
quest_description_hashes: {
      slot: new Fr(6n),
    },
quest_types: {
      slot: new Fr(7n),
    },
quest_tokens: {
      slot: new Fr(8n),
    },
quest_rewards: {
      slot: new Fr(9n),
    },
quest_max_completions: {
      slot: new Fr(10n),
    },
quest_completion_counts: {
      slot: new Fr(11n),
    },
quest_deadlines: {
      slot: new Fr(12n),
    },
quest_statuses: {
      slot: new Fr(13n),
    },
quest_reputation_gates: {
      slot: new Fr(14n),
    },
quest_verifiers: {
      slot: new Fr(15n),
    },
quest_completed_by: {
      slot: new Fr(16n),
    },
quest_completion_proofs: {
      slot: new Fr(17n),
    },
total_quests_created: {
      slot: new Fr(18n),
    },
total_quests_completed: {
      slot: new Fr(19n),
    },
total_rewards_paid: {
      slot: new Fr(20n),
    }
      } as ContractStorageLayout<'admin' | 'quest_count' | 'quest_creators' | 'quest_name_hashes' | 'quest_description_hashes' | 'quest_types' | 'quest_tokens' | 'quest_rewards' | 'quest_max_completions' | 'quest_completion_counts' | 'quest_deadlines' | 'quest_statuses' | 'quest_reputation_gates' | 'quest_verifiers' | 'quest_completed_by' | 'quest_completion_proofs' | 'total_quests_created' | 'total_quests_completed' | 'total_rewards_paid'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_verifier(quest_id: integer, verifier: struct) */
    add_verifier: ((quest_id: (bigint | number), verifier: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** complete_quest(quest_id: integer, verification_hash: field) */
    complete_quest: ((quest_id: (bigint | number), verification_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_quest(name_hash: field, description_hash: field, quest_type: integer, payment_token: struct, reward_per_completion: integer, max_completions: integer, deadline_block: integer, reputation_gate_id: integer, authwit_nonce: field) */
    create_quest: ((name_hash: FieldLike, description_hash: FieldLike, quest_type: (bigint | number), payment_token: AztecAddressLike, reward_per_completion: (bigint | number), max_completions: (bigint | number), deadline_block: (bigint | number), reputation_gate_id: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deactivate_quest(quest_id: integer) */
    deactivate_quest: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_completion_count(quest_id: integer) */
    get_quest_completion_count: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_count() */
    get_quest_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_creator(quest_id: integer) */
    get_quest_creator: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_deadline(quest_id: integer) */
    get_quest_deadline: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_max_completions(quest_id: integer) */
    get_quest_max_completions: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_reputation_gate(quest_id: integer) */
    get_quest_reputation_gate: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_reward(quest_id: integer) */
    get_quest_reward: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_status(quest_id: integer) */
    get_quest_status: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_type(quest_id: integer) */
    get_quest_type: ((quest_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_quests_completed() */
    get_total_quests_completed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_quests_created() */
    get_total_quests_created: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_rewards_paid() */
    get_total_rewards_paid: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** has_completed_quest(quest_id: integer, completer: struct) */
    has_completed_quest: ((quest_id: (bigint | number), completer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_verifier(quest_id: integer, verifier: struct) */
    is_verifier: ((quest_id: (bigint | number), verifier: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_completion(quest_id: integer, completer: struct, verification_hash: field) */
    verify_completion: ((quest_id: (bigint | number), completer: AztecAddressLike, verification_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
