
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import ReputationRegistryContractArtifactJson from '../../../contracts/target/reputation-ReputationRegistry.json' with { type: 'json' };
export const ReputationRegistryContractArtifact = loadContractArtifact(ReputationRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ReputationRegistry;
 */
export class ReputationRegistryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, ReputationRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): ReputationRegistryContract {
    return Contract.at(address, ReputationRegistryContract.artifact, wallet) as ReputationRegistryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<ReputationRegistryContract>(PublicKeys.default(), wallet, ReputationRegistryContractArtifact, (instance, wallet) => ReputationRegistryContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<ReputationRegistryContract>(publicKeys, wallet, ReputationRegistryContractArtifact, (instance, wallet) => ReputationRegistryContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ReputationRegistryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<ReputationRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<ReputationRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      ReputationRegistryContractArtifact,
      (instance, wallet) => ReputationRegistryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ReputationRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(ReputationRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'bounties_completed' | 'bounties_total_earned' | 'hackathons_participated' | 'hackathons_won' | 'grants_received' | 'grants_total_earned' | 'milestones_delivered' | 'quests_completed' | 'peer_give_received' | 'peer_epochs_participated' | 'reputation_scores' | 'reputation_tiers' | 'first_activity_blocks' | 'last_activity_blocks' | 'skill_attestation_counts' | 'skill_highest_levels' | 'gate_count' | 'gate_min_bounties' | 'gate_min_hackathon_wins' | 'gate_min_tier' | 'gate_min_tenure_blocks' | 'gate_active' | 'authorized_updaters' | 'total_contributors'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
bounties_completed: {
      slot: new Fr(3n),
    },
bounties_total_earned: {
      slot: new Fr(4n),
    },
hackathons_participated: {
      slot: new Fr(5n),
    },
hackathons_won: {
      slot: new Fr(6n),
    },
grants_received: {
      slot: new Fr(7n),
    },
grants_total_earned: {
      slot: new Fr(8n),
    },
milestones_delivered: {
      slot: new Fr(9n),
    },
quests_completed: {
      slot: new Fr(10n),
    },
peer_give_received: {
      slot: new Fr(11n),
    },
peer_epochs_participated: {
      slot: new Fr(12n),
    },
reputation_scores: {
      slot: new Fr(13n),
    },
reputation_tiers: {
      slot: new Fr(14n),
    },
first_activity_blocks: {
      slot: new Fr(15n),
    },
last_activity_blocks: {
      slot: new Fr(16n),
    },
skill_attestation_counts: {
      slot: new Fr(17n),
    },
skill_highest_levels: {
      slot: new Fr(18n),
    },
gate_count: {
      slot: new Fr(19n),
    },
gate_min_bounties: {
      slot: new Fr(20n),
    },
gate_min_hackathon_wins: {
      slot: new Fr(21n),
    },
gate_min_tier: {
      slot: new Fr(22n),
    },
gate_min_tenure_blocks: {
      slot: new Fr(23n),
    },
gate_active: {
      slot: new Fr(24n),
    },
authorized_updaters: {
      slot: new Fr(25n),
    },
total_contributors: {
      slot: new Fr(26n),
    }
      } as ContractStorageLayout<'admin' | 'bounties_completed' | 'bounties_total_earned' | 'hackathons_participated' | 'hackathons_won' | 'grants_received' | 'grants_total_earned' | 'milestones_delivered' | 'quests_completed' | 'peer_give_received' | 'peer_epochs_participated' | 'reputation_scores' | 'reputation_tiers' | 'first_activity_blocks' | 'last_activity_blocks' | 'skill_attestation_counts' | 'skill_highest_levels' | 'gate_count' | 'gate_min_bounties' | 'gate_min_hackathon_wins' | 'gate_min_tier' | 'gate_min_tenure_blocks' | 'gate_active' | 'authorized_updaters' | 'total_contributors'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** attest_skill(contributor: struct, skill_hash: field, proficiency_level: integer) */
    attest_skill: ((contributor: AztecAddressLike, skill_hash: FieldLike, proficiency_level: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** authorize_updater(contract_address: struct) */
    authorize_updater: ((contract_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** check_gate(contributor: struct, gate_id: integer) */
    check_gate: ((contributor: AztecAddressLike, gate_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_gate(min_bounties: integer, min_hackathon_wins: integer, min_tier: integer, min_tenure_blocks: integer) */
    create_gate: ((min_bounties: (bigint | number), min_hackathon_wins: (bigint | number), min_tier: (bigint | number), min_tenure_blocks: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deactivate_gate(gate_id: integer) */
    deactivate_gate: ((gate_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_bounties_completed(contributor: struct) */
    get_bounties_completed: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_grants_received(contributor: struct) */
    get_grants_received: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hackathons_won(contributor: struct) */
    get_hackathons_won: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_peer_give_received(contributor: struct) */
    get_peer_give_received: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quests_completed(contributor: struct) */
    get_quests_completed: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reputation_score(contributor: struct) */
    get_reputation_score: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reputation_tier(contributor: struct) */
    get_reputation_tier: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_skill_level(contributor: struct, skill_hash: field) */
    get_skill_level: ((contributor: AztecAddressLike, skill_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_contributors() */
    get_total_contributors: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** record_bounty_completion(contributor: struct, earned_amount: integer) */
    record_bounty_completion: ((contributor: AztecAddressLike, earned_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** record_grant_delivery(contributor: struct, grant_amount: integer) */
    record_grant_delivery: ((contributor: AztecAddressLike, grant_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** record_hackathon_result(contributor: struct, won: boolean) */
    record_hackathon_result: ((contributor: AztecAddressLike, won: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** record_peer_recognition(contributor: struct, give_amount: integer) */
    record_peer_recognition: ((contributor: AztecAddressLike, give_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** record_quest_completion(contributor: struct) */
    record_quest_completion: ((contributor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** revoke_updater(contract_address: struct) */
    revoke_updater: ((contract_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
